chore: updates pre-push lint-staged file

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,1 +1,10 @@
-yarn typecheck && yarn test
+echo "Running pre-push hook..."
+
+yarn typecheck
+
+if [ $? -ne 0 ]; then
+  echo "Typecheck failed. Please fix the errors and try again."
+  exit 1
+fi
+
+exit 0
